ultra64: ultra64::r4300 Class Reference
ultra64::r4300 Class Reference
#include <r4300.h>
Public Member Functions
r4300 ()
~r4300 ()
void step ()
opcode_t * get_instruction (uint32_t addr)
uint32_t get_PC ()
uint64_t get_GPR (uint8_t reg)
uint64_t get_CP0 (uint8_t reg)
Static Private Member Functions
static void not_implemented (r4300 *, opcode_t *)
static void cp0_not_implemented (r4300 *, opcode_t *)
static void special_not_implemented (r4300 *, opcode_t *)
static void beql (r4300 *, opcode_t *)
static void bnel (r4300 *, opcode_t *)
static void bne (r4300 *, opcode_t *)
static void lw (r4300 *, opcode_t *)
static void sw (r4300 *, opcode_t *)
static void andi (r4300 *, opcode_t *)
static void addiu (r4300 *, opcode_t *)
static void ori (r4300 *, opcode_t *)
static void lui (r4300 *, opcode_t *)
static void cp0 (r4300 *, opcode_t *)
static void special (r4300 *cpu, opcode_t *op)
static void move_cp0 (r4300 *, opcode_t *)
static void jr (r4300 *, opcode_t *)
Private Attributes
void(* opcode [0x40])(r4300 *, opcode_t *)
void(* opcode_cp0 [0x40])(r4300 *, opcode_t *)
void(* opcode_special [0x40])(r4300 *, opcode_t *)
std::unordered_map< uint32_t, opcode_t * > op_cache
uint32_t PC = 0
uint64_t GPR [32] = { 0 }
uint64_t CP0 [32] = { 0 }
Detailed Description
Definition at line 33 of file r4300.h.
Constructor & Destructor Documentation
r4300()
ultra64::r4300::r4300 ()
Definition at line 139 of file r4300.cpp.
References _CP0, _SPECIAL, ADDIU, addiu(), ANDI, andi(), BEQL, beql(), BNE, bne(), BNEL, bnel(), cp0(), cp0_not_implemented(), JR, jr(), LUI, lui(), LW, lw(), move_cp0(), not_implemented(), opcode, opcode_cp0, opcode_special, ORI, ori(), PC, special(), SW, and sw().
     {
         PC = 0x1FC00000;
         uint32_t count = 0;
         while(count < 0x40)
         {
             opcode[count] = not_implemented;
             opcode_cp0[count] = cp0_not_implemented;
             count++;
         }
         opcode[BEQL] = beql;
         opcode[BNEL] = bnel;
         opcode[BNE] = bne;
         opcode[LW] = lw;
         opcode[SW] = sw;
         opcode[ANDI] = andi;
         opcode[ADDIU] = addiu;
         opcode[ORI] = ori;
         opcode[LUI] = lui;
         opcode[_CP0] = cp0;
         opcode[_SPECIAL] = special;
         opcode_cp0[0] = move_cp0;
         opcode_special[JR] = jr;
     }
~r4300()
ultra64::r4300::~r4300 ()
Definition at line 168 of file r4300.cpp.
     {
     }
Member Function Documentation
addiu()
void ultra64::r4300::addiu (r4300 * cpu, opcode_t * op) static private
Definition at line 59 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         cpu->GPR[op->rt] = cpu->GPR[op->rs] + (int16_t)(op->offset);
         cpu->PC += 4;
     }
andi()
void ultra64::r4300::andi (r4300 * cpu, opcode_t * op) static private
Definition at line 52 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         cpu->GPR[op->rt] = cpu->GPR[op->rs] & (uint64_t)(op->offset);
         cpu->PC += 4;
     }
beql()
void ultra64::r4300::beql (r4300 * cpu, opcode_t * op) static private
Definition at line 8 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         int32_t branch_offset = ((int16_t)op->offset) << 2;
         uint32_t branch = cpu->PC + branch_offset;
         if(cpu->GPR[op->rs] == cpu->GPR[op->rt]) cpu->PC = branch;
         else cpu->PC += 4;
     }
bne()
void ultra64::r4300::bne (r4300 * cpu, opcode_t * op) static private
Definition at line 31 of file r4300.cpp.
References CP0, cpu, get_instruction(), GPR, ultra64::opcode_t::offset, ultra64::opcode_t::opcode, opcode, PC, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         if(cpu->GPR[op->rs] != cpu->GPR[op->rt])
         {
             opcode_t *delay_op = cpu->get_instruction(cpu->PC + 4);
             try
             {
                 cpu->opcode[delay_op->opcode](cpu, delay_op);
             }
             catch(std::string e)
             {
                 throw e;
             }
             cpu->CP0[9] += 2;
             cpu->PC += (((int16_t)op->offset) << 2) + 4;
         }
         else cpu->PC += 4;
     }
bnel()
void ultra64::r4300::bnel (r4300 * cpu, opcode_t * op) static private
Definition at line 17 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rs, ultra64::opcode_t::rt, and step().
Referenced by r4300().
     {
         int32_t branch_offset = ((int16_t)op->offset) << 2;
         uint64_t branch = cpu->PC + branch_offset + 4;
         if(cpu->GPR[op->rs] != cpu->GPR[op->rt])
         {
             cpu->PC += 4;
             cpu->step();
             cpu->PC = branch;
         }
         else cpu->PC += 8;
     }
cp0()
void ultra64::r4300::cp0 (r4300 * cpu, opcode_t * op) static private
Definition at line 119 of file r4300.cpp.
References cpu, ultra64::opcode_t::function, and opcode_cp0.
Referenced by r4300().
     {
         cpu->opcode_cp0[op->function](cpu, op);
     }
cp0_not_implemented()
void ultra64::r4300::cp0_not_implemented (r4300 * cpu, opcode_t * op) static private
Definition at line 105 of file r4300.cpp.
References get_instruction(), get_PC(), and opcode.
Referenced by r4300().
     {
         char message[1024];
         sprintf(message, "0x%.8X: Instruction 0x%X not implemented.\n", cpu->get_PC(), cpu->get_instruction(cpu->get_PC())->opcode);
         throw std::string(message);
     }
get_CP0()
uint64_t ultra64::r4300::get_CP0 (uint8_t reg)
Definition at line 134 of file r4300.cpp.
References CP0.
Referenced by open_registers().
     {
         return CP0[reg];
     }
get_GPR()
uint64_t ultra64::r4300::get_GPR (uint8_t reg)
Definition at line 129 of file r4300.cpp.
References GPR.
Referenced by open_registers().
     {
         return GPR[reg];
     }
get_instruction()
opcode_t * ultra64::r4300::get_instruction (uint32_t addr)
Definition at line 187 of file r4300.cpp.
References mmu, op_cache, and ultra64::MMU::read_word().
Referenced by bne(), cp0_not_implemented(), not_implemented(), special_not_implemented(), and step().
     {
         uint32_t instruction = mmu->read_word(addr);
         if(op_cache[instruction] == nullptr) op_cache[instruction] = new opcode_t(instruction);
         return op_cache[instruction];
     }
get_PC()
uint32_t ultra64::r4300::get_PC ()
Definition at line 124 of file r4300.cpp.
References PC.
Referenced by cp0_not_implemented(), not_implemented(), DebuggerWindow::OnCPUStep(), DebuggerWindow::OnCPUSteps(), open_registers(), special_not_implemented(), and DebuggerWindow::view().
     {
         return PC;
     }
jr()
void ultra64::r4300::jr (r4300 * cpu, opcode_t * op) static private
Definition at line 10 of file special.cpp.
References GPR, PC, ultra64::opcode_t::rs, and step().
Referenced by r4300().
     {
         uint32_t branch = cpu->GPR[op->rs];
         cpu->PC += 4;
         cpu->step();
         cpu->PC = branch;
     }
lui()
void ultra64::r4300::lui (r4300 * cpu, opcode_t * op) static private
Definition at line 65 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         cpu->GPR[op->rt] = (uint64_t)(op->offset) * 0x10000;
         cpu->PC += 4;
     }
lw()
void ultra64::r4300::lw (r4300 * cpu, opcode_t * op) static private
Definition at line 71 of file r4300.cpp.
References ultra64::opcode_t::base, GPR, mmu, ultra64::opcode_t::offset, PC, ultra64::MMU::read_word(), and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         try
         {
             cpu->GPR[op->rt] = mmu->read_word(cpu->GPR[op->base] + op->offset);
         }
         catch(std::string e)
         {
             throw e;
         }
         cpu->PC += 4;
     }
move_cp0()
void ultra64::r4300::move_cp0 (r4300 * cpu, opcode_t * op) static private
Definition at line 5 of file cp0.cpp.
References CP0, GPR, MFC0, MTC0, PC, ultra64::opcode_t::rd, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         switch(op->rs)
         {
             case MTC0: /* To */
                 cpu->CP0[op->rd] = cpu->GPR[op->rt];
                 cpu->PC += 4;
                 return;
                 break;
             case MFC0: /* From */
                 cpu->GPR[op->rt] = cpu->CP0[op->rd];
                 cpu->PC += 4;
                 return;
                 break;
         }
     }
not_implemented()
void ultra64::r4300::not_implemented (r4300 * cpu, opcode_t * op) static private
Definition at line 98 of file r4300.cpp.
References get_instruction(), and get_PC().
Referenced by r4300().
     {
         char message[1024];
         sprintf(message, "0x%.8X: NOT IMPLEMENTED %s\n", cpu->get_PC(), cpu->get_instruction(cpu->get_PC())->to_string().c_str());
         throw std::string(message);
     }
ori()
void ultra64::r4300::ori (r4300 * cpu, opcode_t * op) static private
Definition at line 92 of file r4300.cpp.
References GPR, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rs, and ultra64::opcode_t::rt.
Referenced by r4300().
     {
         cpu->GPR[op->rt] = cpu->GPR[op->rs] | (uint64_t)(op->offset);
         cpu->PC += 4;
     }
special()
void ultra64::r4300::special (r4300 * cpu, opcode_t * op) static private
Definition at line 5 of file special.cpp.
References cpu, ultra64::opcode_t::function, and opcode_special.
Referenced by r4300().
     {
         cpu->opcode_special[op->function](cpu, op);
     }
special_not_implemented()
void ultra64::r4300::special_not_implemented (r4300 * cpu, opcode_t * op) static private
Definition at line 112 of file r4300.cpp.
References get_instruction(), get_PC(), and opcode.
     {
         char message[1024];
         sprintf(message, "0x%.8X: Instruction 0x%X not implemented.\n", cpu->get_PC(), cpu->get_instruction(cpu->get_PC())->opcode);
         throw std::string(message);
     }
step()
void ultra64::r4300::step ()
Definition at line 172 of file r4300.cpp.
References CP0, get_instruction(), ultra64::opcode_t::opcode, opcode, and PC.
Referenced by bnel(), jr(), DebuggerWindow::OnCPUStep(), and DebuggerWindow::OnCPUSteps().
     {
         opcode_t *op = get_instruction(PC);
         try
         {
             opcode[op->opcode](this, op);
         }
         catch(std::string e)
         {
             throw e;
         }
         CP0[9] += 2;
     }
sw()
void ultra64::r4300::sw (r4300 * cpu, opcode_t * op) static private
Definition at line 84 of file r4300.cpp.
References ultra64::opcode_t::base, GPR, mmu, ultra64::opcode_t::offset, PC, ultra64::opcode_t::rt, and ultra64::MMU::write_word().
Referenced by r4300().
     {
         try {
             mmu->write_word(cpu->GPR[op->base] + (int16_t)(op->offset), (cpu->GPR[op->rt] & 0xFFFFFFFF));
         } catch(std::string e) { throw e; }
         cpu->PC += 4;
     }
Member Data Documentation
CP0
uint64_t ultra64::r4300::CP0[32] = { 0 } private
Definition at line 50 of file r4300.h.
Referenced by bne(), get_CP0(), move_cp0(), and step().
GPR
uint64_t ultra64::r4300::GPR[32] = { 0 } private
Definition at line 49 of file r4300.h.
Referenced by addiu(), andi(), beql(), bne(), bnel(), get_GPR(), jr(), lui(), lw(), move_cp0(), ori(), and sw().
op_cache
std::unordered_map<uint32_t, opcode_t *> ultra64::r4300::op_cache private
Definition at line 47 of file r4300.h.
Referenced by get_instruction().
opcode
void(* ultra64::r4300::opcode[0x40])(r4300 *, opcode_t *) private
Definition at line 44 of file r4300.h.
Referenced by bne(), cp0_not_implemented(), ultra64::opcode_t::decode_instruction(), r4300(), special_not_implemented(), step(), and ultra64::opcode_t::to_string().
opcode_cp0
void(* ultra64::r4300::opcode_cp0[0x40])(r4300 *, opcode_t *) private
Definition at line 45 of file r4300.h.
Referenced by cp0(), and r4300().
opcode_special
void(* ultra64::r4300::opcode_special[0x40])(r4300 *, opcode_t *) private
Definition at line 46 of file r4300.h.
Referenced by r4300(), and special().
PC
uint32_t ultra64::r4300::PC = 0 private
Definition at line 48 of file r4300.h.
Referenced by addiu(), andi(), beql(), bne(), bnel(), get_PC(), jr(), lui(), lw(), move_cp0(), ori(), r4300(), step(), and sw().
The documentation for this class was generated from the following files:
include/r4300.h
src/r4300/cp0.cpp
src/r4300/r4300.cpp
src/r4300/special.cpp