ultra64: MainWindow Class Reference
MainWindow Class Reference
#include <ultra64.h>
Public Member Functions
MainWindow (const wxString &title, const wxPoint &pos, const wxSize &size)
Private Member Functions
void OnOpenROM (wxCommandEvent &event)
void OnOpenPIFROM (wxCommandEvent &event)
void OnExit (wxCommandEvent &event)
void OnAbout (wxCommandEvent &event)
void OnDebugPIFROM (wxCommandEvent &event)
void OnDebugROM (wxCommandEvent &event)
void OnDebugRegisters (wxCommandEvent &event)
wxDECLARE_EVENT_TABLE ()
Detailed Description
Definition at line 4 of file ultra64.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (const wxString & title, const wxPoint & pos, const wxSize & size)
Definition at line 113 of file ultra64.cpp.
References ID_debug_pif_rom, ID_debug_registers, ID_debug_rom, ID_open_pif_rom, and ID_open_rom.
         : wxFrame(NULL, wxID_ANY, title, pos, size)
 {
     this->SetBackgroundColour(wxColour(*wxBLACK));
     wxMenu *menuFile = new wxMenu;
     menuFile->Append(ID_open_pif_rom, "Load &PIF ROM...","");
     menuFile->Append(ID_open_rom, "&Open ROM...\tCtrl-H",
                      "");
     menuFile->AppendSeparator();
     menuFile->Append(wxID_EXIT);
     wxMenu *menuHelp = new wxMenu;
     menuHelp->Append(wxID_ABOUT);
     wxMenu *menuDebug = new wxMenu;
     menuDebug->Append(ID_debug_pif_rom, "View &PIF ROM", "");
     menuDebug->Append(ID_debug_rom, "View &ROM", "");
     menuDebug->Append(ID_debug_registers, "View R&egisters", "");
     wxMenuBar *menuBar = new wxMenuBar;
     menuBar->Append(menuFile, "&File");
     menuBar->Append(menuDebug, "&Debug");
     menuBar->Append(menuHelp, "&Help");
     SetMenuBar(menuBar);
     CreateStatusBar(1);
     SetStatusText(wxT("Ready"), 0);
 }
Member Function Documentation
OnAbout()
void MainWindow::OnAbout (wxCommandEvent & event) private
Definition at line 148 of file ultra64.cpp.
 {
     wxMessageBox( "This is a wxWidgets' Hello world sample",
                   "About Hello World", wxOK | wxICON_INFORMATION );
 }
OnDebugPIFROM()
void MainWindow::OnDebugPIFROM (wxCommandEvent & event) private
Definition at line 290 of file ultra64.cpp.
References open_debugger().
 {
     open_debugger();
     wxGetApp().debugger->view(0x1FC00000, 0x1FC007BF);
 }
OnDebugRegisters()
void MainWindow::OnDebugRegisters (wxCommandEvent & event) private
Definition at line 285 of file ultra64.cpp.
References open_registers().
 {
     open_registers();
 }
OnDebugROM()
void MainWindow::OnDebugROM (wxCommandEvent & event) private
Definition at line 296 of file ultra64.cpp.
References open_debugger().
 {
     open_debugger();
     wxGetApp().debugger->view(0x10000000, 0x10008000);
 }
OnExit()
void MainWindow::OnExit (wxCommandEvent & event) private
Definition at line 143 of file ultra64.cpp.
 {
     Close(true);
 }
OnOpenPIFROM()
void MainWindow::OnOpenPIFROM (wxCommandEvent & event) private
Definition at line 154 of file ultra64.cpp.
References ultra64::PIF_ROM::get_pointer(), and ultra64::MMU::write_word().
 {
     wxFileDialog rom_dialog(this, _("Open PIF ROM file"), "", "",
                                 "ROM files (*.bin)|*.bin|All files (*.*)|*.*",
                                 wxFD_OPEN|wxFD_FILE_MUST_EXIST);
     if(wxID_CANCEL == rom_dialog.ShowModal()) return;
     std::string filename = rom_dialog.GetPath().ToStdString();
     if(!filename.size()) return;
     try
     {
         pif_rom = new ultra64::PIF_ROM(filename);
     }
     catch(std::string e)
     {
         std::cout << e << std::endl;
         return;
     }
     uint32_t count = 0;
     uint32_t *p = (uint32_t *)pif_rom->get_pointer();
     while(count < 0x7C0)
     {
         mmu->write_word(0x1FC00000 + count, p[count / 4]);
         count += 4;
     }
 }
OnOpenROM()
void MainWindow::OnOpenROM (wxCommandEvent & event) private
Definition at line 185 of file ultra64.cpp.
References ultra64::MMU::attach_rom(), ultra64::ROM::get_header(), ultra64::ROM::get_pointer(), ultra64::ROM::get_size(), and ultra64::ROM_header::name.
 {
     wxFileDialog rom_dialog(this, _("Open N64 ROM file"), "", "",
                                 "N64 ROM files (*.n64;*.v64;*.z64;*.bin)|*.n64;*.v64;*.bin|All files (*.*)|*.*",
                                 wxFD_OPEN|wxFD_FILE_MUST_EXIST);
     if(wxID_CANCEL == rom_dialog.ShowModal()) return;
     std::string filename = rom_dialog.GetPath().ToStdString();
     if(!filename.size()) return;
     try
     {
         rom = new ultra64::ROM(filename);
     }
     catch(std::string e)
     {
         std::cout << e << std::endl;
         return;
     }
     mmu->attach_rom(rom->get_pointer(), rom->get_size());
     std::stringstream ss;
     ultra64::ROM_header header = rom->get_header();
     ss << "Ultra 64 - " << header.name;
     wxTopLevelWindow::SetTitle(ss.str());
 }
wxDECLARE_EVENT_TABLE()
MainWindow::wxDECLARE_EVENT_TABLE () private
The documentation for this class was generated from the following files:
include/ultra64.h
src/ultra64.cpp