ultra64: ultra64::MMU Class Reference
ultra64::MMU Class Reference
#include <memory.h>
Public Member Functions
MMU ()
~MMU ()
void attach_rom (unsigned char *rom, size_t sz)
uint8_t read_byte (uint32_t addr)
uint16_t read_hword (uint32_t addr)
uint32_t read_word (uint32_t addr)
void write_byte (uint32_t addr, uint8_t value)
void write_hword (uint32_t addr, uint16_t value)
void write_word (uint32_t addr, uint32_t value)
Private Member Functions
memory_section get_section (uint32_t addr)
Private Attributes
unsigned char * pif_rom = new unsigned char[0x7C0]
unsigned char * pif_ram = new unsigned char[0x40]
unsigned char * rom = nullptr
size_t rom_sz = 0
unsigned char * rdram = new unsigned char[0x400000]
unsigned char * rdram_registers = new unsigned char[0x28]
unsigned char * sp_dmem = new unsigned char[0x1000]
unsigned char * sp_imem = new unsigned char[0x1000]
unsigned char * sp_registers = new unsigned char[0x20]
unsigned char * sp_registers2 = new unsigned char[0x8]
unsigned char * pi_registers = new unsigned char[0x34]
unsigned char * vi_registers = new unsigned char[0x38]
unsigned char * ai_registers = new unsigned char[0x18]
unsigned char * dp_command_registers = new unsigned char[0x20]
unsigned char * dp_span_registers = new unsigned char[0x10]
unsigned char * mi_registers = new unsigned char[0x10]
unsigned char * ri_registers = new unsigned char[0x20]
unsigned char * si_registers = new unsigned char[0x1C]
Detailed Description
Definition at line 14 of file memory.h.
Constructor & Destructor Documentation
MMU()
ultra64::MMU::MMU ()
Definition at line 7 of file memory.cpp.
     {
     }
~MMU()
ultra64::MMU::~MMU ()
Definition at line 11 of file memory.cpp.
     {
     }
Member Function Documentation
attach_rom()
void ultra64::MMU::attach_rom (unsigned char * rom, size_t sz)
Definition at line 15 of file memory.cpp.
References rom, and rom_sz.
Referenced by MainWindow::OnOpenROM().
     {
         this->rom = rom;
         rom_sz = sz;
     }
get_section()
memory_section ultra64::MMU::get_section (uint32_t addr) private
Definition at line 162 of file memory.cpp.
References ai_registers, dp_command_registers, dp_span_registers, mi_registers, ultra64::memory_section::offset, pi_registers, pif_ram, pif_rom, ultra64::memory_section::ptr, rdram, rdram_registers, ri_registers, rom, rom_sz, si_registers, sp_dmem, sp_imem, sp_registers, sp_registers2, and vi_registers.
Referenced by read_byte(), read_hword(), read_word(), write_byte(), write_hword(), and write_word().
     {
         memory_section section;
         std::stringstream ss;
         std::string e;
         if((addr >= 0x00000000) && (addr <=0x003FFFFF))
         {
             section.offset = 0x0;
             section.ptr = rdram;
             return section;
         }
         if((addr >= 0x03F00000) && (addr <= 0x03FFFFFF))
         {
             section.offset = 0x03F00000;
             section.ptr = rdram_registers;
             return section;
         }
         if((addr >= 0x04000000) && (addr <= 0x04000FFF))
         {
             section.offset = 0x04000000;
             section.ptr = sp_dmem;
             return section;
         }
         if((addr >= 0x04001000) && (addr <= 0x04001FFF))
         {
             section.offset = 0x04001000;
             section.ptr = sp_imem;
             return section;
         }
         if((addr >= 0x04040000) && (addr <= 0x0404001F))
         {
             section.offset = 0x04040000;
             section.ptr = sp_registers;
             return section;
         }
         if((addr >= 0x04080000) && (addr <= 0x04080007))
         {
             section.offset = 0x04080000;
             section.ptr = sp_registers2;
             return section;
         }
         if((addr >= 0x04100000) && (addr <= 0x0410001F))
         {
             section.offset = 0x04100000;
             section.ptr = dp_command_registers;
             return section;
         }
         if((addr >= 0x04200000) && (addr <= 0x0420000F))
         {
             section.offset = 0x04200000;
             section.ptr = dp_span_registers;
             return section;
         }
         if((addr >= 0x04300000) && (addr <= 0x0430000F))
         {
             section.offset = 0x04300000;
             section.ptr = mi_registers;
             return section;
         }
         if((addr >= 0x04400000) && (addr <= 0x04400037))
         {
             section.offset = 0x04400000;
             section.ptr = vi_registers;
             return section;
         }
         if((addr >= 0x04500000) && (addr <= 0x04500017))
         {
             section.offset = 0x04500000;
             section.ptr = ai_registers;
             return section;
         }
         if((addr >= 0x04600000) && (addr <= 0x04600033))
         {
             section.offset = 0x04600000;
             section.ptr = pi_registers;
             return section;
         }
         if((addr >= 0x04700000) && (addr <= 0x0440001F))
         {
             section.offset = 0x04700000;
             section.ptr = ri_registers;
             return section;
         }
         if((addr >= 0x04800000) && (addr <= 0x0480001B))
         {
             section.offset = 0x04800000;
             section.ptr = si_registers;
             return section;
         }
         if((addr >= 0x10000000) && (addr <=0x1FBFFFFF))
     {
             section.offset = 0x10000000;
             if((addr - section.offset) > rom_sz)
             {
                 ss << "ROM physical address 0x" << std::hex << addr << " is out of bounds.";
                 std::string e = ss.str();
                 throw e;
             }
         section.ptr = rom;
             return section;
     }
         if((addr >= 0x1FC00000) && (0x1FC007BF))
         {
             section.offset = 0x1FC00000;
             section.ptr = pif_rom;
             return section;
         }
         if((addr >= 0x1FC007C0) && (0x1FC007FF))
         {
             section.offset = 0x1FC007c0;
             section.ptr = pif_ram;
             return section;
         }
         ss << "Address 0x" << std::hex << addr << " is out of bounds.";
         e = ss.str();
         throw e;
     }
read_byte()
uint8_t ultra64::MMU::read_byte (uint32_t addr)
Definition at line 21 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
     {
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         memory_section s;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint8_t *p = (uint8_t *)s.ptr;
         return p[phys_addr - s.offset];
     }
read_hword()
uint16_t ultra64::MMU::read_hword (uint32_t addr)
Definition at line 58 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
     {
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         memory_section s;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint32_t pointer = phys_addr - s.offset;
         if(pointer) pointer /= 2;
         uint16_t *p = (uint16_t *)s.ptr;
         return p[pointer];
     }
read_word()
uint32_t ultra64::MMU::read_word (uint32_t addr)
Definition at line 101 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
Referenced by ultra64::r4300::get_instruction(), ultra64::r4300::lw(), and DebuggerWindow::view().
     {
         memory_section s;
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint32_t pointer = phys_addr - s.offset;
         if(pointer) pointer /= 4;
         uint32_t *p = (uint32_t *)s.ptr;
         uint32_t value;
         asm ("movl %1, %%eax;"
               "bswap %%eax;"
               "movl %%eax, %0;"
              :"=r"(value)        /* output */
              :"r"(p[pointer])         /* input */
              :"%eax"         /* clobbered register */
          );
         return value;
     }
write_byte()
void ultra64::MMU::write_byte (uint32_t addr, uint8_t value)
Definition at line 40 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
     {
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         memory_section s;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint8_t *p = (uint8_t *)s.ptr;
         p[phys_addr - s.offset] = value;
     }
write_hword()
void ultra64::MMU::write_hword (uint32_t addr, uint16_t value)
Definition at line 80 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
     {
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         memory_section s;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint32_t pointer = phys_addr - s.offset;
         if(pointer) pointer /= 2;
         uint16_t *p = (uint16_t *)s.ptr;
         p[pointer] = value;
     }
write_word()
void ultra64::MMU::write_word (uint32_t addr, uint32_t value)
Definition at line 134 of file memory.cpp.
References get_section(), ultra64::memory_section::offset, and ultra64::memory_section::ptr.
Referenced by MainWindow::OnOpenPIFROM(), ultra64::rsp::rsp(), and ultra64::r4300::sw().
     {
         memory_section s;
         uint32_t phys_addr = addr & 0x1FFFFFFF;
         try
         {
             s = get_section(phys_addr);
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
             exit(-1);
         }
         uint32_t pointer = phys_addr - s.offset;
         if(pointer) pointer /= 4;
         uint32_t *p = (uint32_t *)s.ptr;
         asm ("movl %1, %%eax;"
               "bswap %%eax;"
               "movl %%eax, %0;"
              :"=r"(p[pointer])        /* output */
              :"r"(value)         /* input */
              :"%eax"         /* clobbered register */
          );
     }
Member Data Documentation
ai_registers
unsigned char* ultra64::MMU::ai_registers = new unsigned char[0x18] private
Definition at line 41 of file memory.h.
Referenced by get_section().
dp_command_registers
unsigned char* ultra64::MMU::dp_command_registers = new unsigned char[0x20] private
Definition at line 42 of file memory.h.
Referenced by get_section().
dp_span_registers
unsigned char* ultra64::MMU::dp_span_registers = new unsigned char[0x10] private
Definition at line 43 of file memory.h.
Referenced by get_section().
mi_registers
unsigned char* ultra64::MMU::mi_registers = new unsigned char[0x10] private
Definition at line 44 of file memory.h.
Referenced by get_section().
pi_registers
unsigned char* ultra64::MMU::pi_registers = new unsigned char[0x34] private
Definition at line 39 of file memory.h.
Referenced by get_section().
pif_ram
unsigned char* ultra64::MMU::pif_ram = new unsigned char[0x40] private
Definition at line 30 of file memory.h.
Referenced by get_section().
pif_rom
unsigned char* ultra64::MMU::pif_rom = new unsigned char[0x7C0] private
Definition at line 29 of file memory.h.
Referenced by get_section().
rdram
unsigned char* ultra64::MMU::rdram = new unsigned char[0x400000] private
Definition at line 33 of file memory.h.
Referenced by get_section().
rdram_registers
unsigned char* ultra64::MMU::rdram_registers = new unsigned char[0x28] private
Definition at line 34 of file memory.h.
Referenced by get_section().
ri_registers
unsigned char* ultra64::MMU::ri_registers = new unsigned char[0x20] private
Definition at line 45 of file memory.h.
Referenced by get_section().
rom
unsigned char* ultra64::MMU::rom = nullptr private
Definition at line 31 of file memory.h.
Referenced by attach_rom(), and get_section().
rom_sz
size_t ultra64::MMU::rom_sz = 0 private
Definition at line 32 of file memory.h.
Referenced by attach_rom(), and get_section().
si_registers
unsigned char* ultra64::MMU::si_registers = new unsigned char[0x1C] private
Definition at line 46 of file memory.h.
Referenced by get_section().
sp_dmem
unsigned char* ultra64::MMU::sp_dmem = new unsigned char[0x1000] private
Definition at line 35 of file memory.h.
Referenced by get_section().
sp_imem
unsigned char* ultra64::MMU::sp_imem = new unsigned char[0x1000] private
Definition at line 36 of file memory.h.
Referenced by get_section().
sp_registers
unsigned char* ultra64::MMU::sp_registers = new unsigned char[0x20] private
Definition at line 37 of file memory.h.
Referenced by get_section().
sp_registers2
unsigned char* ultra64::MMU::sp_registers2 = new unsigned char[0x8] private
Definition at line 38 of file memory.h.
Referenced by get_section().
vi_registers
unsigned char* ultra64::MMU::vi_registers = new unsigned char[0x38] private
Definition at line 40 of file memory.h.
Referenced by get_section().
The documentation for this class was generated from the following files:
include/memory.h
src/memory.cpp