ultra64: src/ultra64.cpp File Reference
ultra64.cpp File Reference
#include <wx/wx.h>
#include <sstream>
#include <chrono>
#include <ultra64.h>
#include <rom.h>
#include <pif_rom.h>
#include <memory.h>
#include <r4300.h>
#include <rsp.h>
Functions
void open_registers ()
wxBEGIN_EVENT_TABLE (MainWindow, wxFrame) wxEND_EVENT_TABLE() wxBEGIN_EVENT_TABLE(DebuggerWindow
wxFrame wxEND_EVENT_TABLE () wxIMPLEMENT_APP(wxUltra64)
void open_debugger ()
Variables
ultra64::ROM * rom
ultra64::PIF_ROM * pif_rom
ultra64::MMU * mmu = new ultra64::MMU()
ultra64::r4300 * cpu = new ultra64::r4300()
ultra64::rsp * rsp = new ultra64::rsp()
Function Documentation
open_debugger()
void open_debugger ()
Definition at line 180 of file ultra64.cpp.
References BUTTON_cpu_step, and ID_MEMORY_LISTBOX.
Referenced by MainWindow::OnDebugPIFROM(), and MainWindow::OnDebugROM().
 {
     if(!wxGetApp().debugger)
     {
         wxGetApp().debugger = new DebuggerWindow(wxGetApp().frame,
                               "Ultra 64 Debugger", wxPoint(150, 50), wxSize(700, 480));
     }
     wxGetApp().debugger->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().debugger->Show(true);
     wxFont font(wxFontInfo(14).Bold());
     wxStaticText *label_memory_address = new wxStaticText(wxGetApp().debugger,
                             wxID_ANY, wxT("Address      Data"), wxPoint(20, 5));
     label_memory_address->SetFont(font);
     wxFont mem_font(wxFontInfo(12).FaceName("Courier"));
     wxGetApp().debugger->memory_listbox = new wxListBox(wxGetApp().debugger, ID_MEMORY_LISTBOX,
       wxPoint(20, 30), wxSize(550, 380));
     wxGetApp().debugger->memory_listbox->SetFont(mem_font);
     wxGetApp().debugger->cpu_step = new wxButton(wxGetApp().debugger, BUTTON_cpu_step, _T("Step"),
                                                  wxPoint(580, 30), wxDefaultSize, 0);
 }
open_registers()
void open_registers ()
Definition at line 204 of file ultra64.cpp.
References ultra64::r4300::get_CP0(), ultra64::r4300::get_GPR(), ultra64::r4300::get_PC(), and ID_REGISTERS_LISTBOX.
Referenced by DebuggerWindow::OnCPUStep(), and MainWindow::OnDebugRegisters().
 {
     if(!wxGetApp().registers)
     {
         wxGetApp().registers = new RegistersWindow(wxGetApp().frame,
                                "Registers", wxPoint(200, 50), wxSize(820, 450));
     }
     wxGetApp().registers->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().registers->Show(true);
     wxFont font(wxFontInfo(14).Bold());
     wxStaticText *label_registers = new wxStaticText(wxGetApp().registers,
                             wxID_ANY, wxT("Registers"), wxPoint(20, 5));
     label_registers->SetFont(font);
     wxFont reg_font(wxFontInfo(12).FaceName("Courier"));
     wxGetApp().registers->registers_listbox = new wxListBox(wxGetApp().registers, ID_REGISTERS_LISTBOX,
       wxPoint(20, 30), wxSize(780, 380));
     wxGetApp().registers->registers_listbox->SetFont(reg_font);
     char temp[1024];
     uint32_t count = 0;
     while(count < 32)
     {
         sprintf(temp, "GPR[%.2d]=0x%.8llX  GPR[%.2d]=0x%.8llX  CP0[%.2d]=0x%.8llX  CP0[%.2d]=0x%.8llX",
                 count, cpu->get_GPR(count), count + 1, cpu->get_GPR(count + 1),
                 count, cpu->get_CP0(count), count + 1, cpu->get_CP0(count + 1));
         wxGetApp().registers->registers_listbox->Append(temp);
         count += 2;
     }
     sprintf(temp, "PC = 0x%.8X", cpu->get_PC());
     wxGetApp().registers->registers_listbox->Append(temp);
 }
wxBEGIN_EVENT_TABLE()
wxBEGIN_EVENT_TABLE (MainWindow , wxFrame)
wxEND_EVENT_TABLE()
wxFrame wxEND_EVENT_TABLE ()
Variable Documentation
cpu
ultra64::r4300* cpu = new ultra64::r4300()
Definition at line 15 of file ultra64.cpp.
Referenced by ultra64::r4300::bne(), ultra64::r4300::cp0(), and ultra64::r4300::special().
mmu
ultra64::MMU* mmu = new ultra64::MMU()
Definition at line 14 of file ultra64.cpp.
Referenced by ultra64::r4300::get_instruction(), ultra64::r4300::lw(), ultra64::rsp::rsp(), and ultra64::r4300::sw().
pif_rom
ultra64::PIF_ROM* pif_rom
Definition at line 13 of file ultra64.cpp.
rom
ultra64::ROM* rom
Definition at line 12 of file ultra64.cpp.
rsp
ultra64::rsp* rsp = new ultra64::rsp()
Definition at line 16 of file ultra64.cpp.